### ISSUE TITLE
Can't enter text into input fields while in fullscreen mode in Chrome/Safari on Mac

### ISSUE THREAD

**Issue by bostondevin** [kayahr/jquery-fullscreen-plugin#10]
In Chrome and Safari on a Mac, i'm noticing that when you enter into fullscreen mode you can no longer enter any characters besides spaces into text input fields on the html page you just made full screen. It works fine on firefox.

**Comment by JWEsposito** [comment]
Hello- could some please provide some initial/remedial instructions on how to implement the fix? Am I downloading a snippet of code and moving to my applications (MAC) folder? I would like to be able to enter text in full screen mode. 
Joe
