### ISSUE TITLE
Error in production use

### ISSUE THREAD

**Issue by timtribers** [kayahr/jquery-fullscreen-plugin#39]
Don't know if this plugin is still developed, but we use it in production and pick up any errors.  Here's one we have just seen:

`TypeError: this.media.webkitEnterFullscreen is not a function. (In 'this.media.webkitEnterFullscreen()', 'this.media.webkitEnterFullscreen' is undefined
`

Sorry, no idea of platform or browser.

**Comment by williamdes** [comment]
See: https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1633500-webkitenterfullscreen

I can not find any code that mentions `webkitEnterFullscreen` in https://github.com/code-lts/jquery-fullscreen-plugin/blob/master/jquery.fullscreen.js

So I am closing this as I think it's code in your codebase that is causing this :)

**Comment by timtribers** [comment]
Apologies @williamdes 

Have scanned my code and jQuery itself and cannot find this either.  Very strange.
Sorry to have bothered you.

**Comment by williamdes** [comment]
That's okay, have a nice day !
